import Section from "@/components/Section";
import StyledMarkdown from "@/components/StyledMarkdown";

export default function AIPage() {
  const content = `
# AI Policy

The following is my personal policy for AI usage. It governs how I permit myself to use
large language models and generative AI. I do not expect others to abide by these principles;
it is here so I can hold myself accountable and point to it when people ask how I use AI.

As generative AI technologies are constantly evolving, I may change this policy in the future.

## Terminology

I avoid using the general term "AI" when a more precise term is appropriate. I prefer these terms:

- "Generative AI" refers to the class of machine learning models that produce images, video, audio, text, or other media content. 
- "Large language model" (LLM) describes a specific type of generative AI that receives text as an input and generates text as a response.

## Principles

I do not provide my own personal information or the personal information of others
to LLMs. I never send LLM-produced work to others without reviewing it completely first.

I do not use LLMs to produce English writing that I later implicitly or explicitly pass off as my own.
If I include LLM-produced English writing in a written work of my own, I explicitly mark it as LLM-produced.
When writing in languages other than English, I may use LLMs to review drafts so that I may 
reduce errors and improve clarity and idiomaticity.

I sometimes use LLMs to write code. I do not ask others to review code generated by an LLM on my behalf
without thoroughly reviewing it myself first. I use LLMs to search through, understand, modify, 
and debug existing code.

I do not use generative AI to create image or video content. I may use generative AI image editing
tools (such as Adobe Lightroom's Generative Remove) to edit content of existing images.

## Recommended reading

- [Writes and Write-Nots](https://paulgraham.com/writes.html)

Inspired by [Sloane's AI policy](https://sloanelybutsurely.com/ai/) and [the /ai 'manifesto'](https://www.bydamo.la/p/ai-manifesto)
`;

  return (
    <Section>
      <div className="max-w-2xl mx-auto font-noto-sans p-2 md:p-6 text-left leading-7">
        <StyledMarkdown>
          {content}
        </StyledMarkdown>
      </div>
    </Section>
  );
}
